[package]
name = "propresenter-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.1"
protobuf = "3.5.0"

[build-dependencies]
glob = "0.3.1"
prost-build = "0.13.1"
protoc-bin-vendored = "3.0.0"
