[package]
name = "propresenter-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
protobuf = "3.5.0"

[build-dependencies]
glob = "0.3.1"
#itertools = "0.13.0"
protobuf-codegen = "3.5.0"
protoc-bin-vendored = "3.0.0"
